---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workload
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./sidero/cluster/workload
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
