---
helm:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 30.1.0

dependsOn:
  - name: observability-grafana-agent-cluster

values:
  deployment:
    replicas: 3
  service:
    type: LoadBalancer
    annotations:
      "iolbipam.cilium.io/ips": "192.168.2.100"
  logs:
    general:
      format: json
      level: DEBUG
    access:
      enabled: true
      format: json
  ingressClass:
    enabled: true
    isDefaultClass: true
    fallbackApiVersion: v1
  globalArguments:
    - --serverstransport.insecureskipverify=true
    - --providers.kubernetesingress.ingressclass=traefik
    - --metrics.prometheus=true
    - --metrics.prometheus.entryPoint=metrics
  ports:
    web:
      redirectTo:
        port: websecure
    websecure:
      tls:
        enabled: true
        options: default
    metrics:
      port: 8082
      expose:
        default: true
      exposedPort: 8082
