{
 "title": "Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Cisco Switch Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cisco_telnet_temp" }
   ]
  },
  {
   "title": "Rack Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "power_mw{host=\"192.168.1.156:9999\"}"
    }
   ]
  },
  {
   "title": "Switch Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "cisco_power_used" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}