{
 "title": "Home Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "download_rate_bits != 0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Upload Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "upload_rate_bits != 0", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    { "expr": "current_ma" }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    { "expr": "voltage_mv" }
   ]
  },
  {
   "title": "Watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    { "expr": "power_mw" }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "battery", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "humidity", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Occupancy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "occupancy", "legendFormat": "{{sensor}}" }
   ]
  }
 ]
}