{
 "title": "Network Overview",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"192.168.1.1:9100\"} - node_boot_time_seconds{instance=\"192.168.1.1:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} - node_memory_SwapFree_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) / (node_memory_SwapTotal_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} )) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}"
    }
   ]
  },
  {
   "title": "ROOT Fs Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} - node_memory_MemFree_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} - (node_memory_Cached_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} + node_memory_Buffers_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"})"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"} - node_memory_SwapFree_bytes{instance=\"192.168.1.1:9100\", job=\"pfsense-metrics\"})"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Node Exporter Scrape",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_success{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}",
     "legendFormat": "{{collector}}"
    },
    {
     "expr": "node_textfile_scrape_error{instance=\"192.168.1.1:9100\",job=\"pfsense-metrics\"}"
    }
   ]
  }
 ]
}