FROM golang:1.22 AS builder

WORKDIR /template

COPY ./hack/template/ ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /mirdain

FROM alpine:3.20.2

COPY --from=builder /mirdain /mirdain

RUN apk add --update curl bash

RUN curl -s https://fluxcd.io/install.sh | bash
RUN apk add --update docker openrc
RUN apk add --update kubectl helm yq --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

RUN mkdir -p /output

CMD ["/mirdain"]
