---
helm:
  repo: https://bjw-s.github.io/helm-charts
  chart: app-template
  version: 3.7.3

backup:
  pvc: "radarr-config"

values:
  automountServiceAccountToken: false
  controller:
    type: statefulset
  image:
    repository: ghcr.io/onedr0p/radarr
    tag: 5.8.3
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups:
      - 100
  service:
    main:
      ports:
        http:
          port: 7878
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: radarr.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: radarr-tls
          hosts:
            - radarr.${SECRET_DOMAIN}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    config:
      enabled: true
      mountPath: /config
      size: 5Gi
    media:
      enabled: true
      type: nfs
      server: narya.${SECRET_INTERNAL_DOMAIN}
      path: /mnt/data/media
      mountPath: /data
