---
helm:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  version: 1.5.1

backup:
  pvc: "sabnzbd-config"

values:
  automountServiceAccountToken: false
  controller:
    type: statefulset
  env:
    SABNZBD__HOST_WHITELIST_ENTRIES: >-
      sabnzbd,
      sabnzbd.default,
      sabnzbd.default.svc,
      sabnzbd.default.svc.cluster,
      sabnzbd.default.svc.cluster.local,
      sabnzbd.${SECRET_DOMAIN}
  image:
    repository: ghcr.io/onedr0p/sabnzbd
    tag: 4.3.2
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups:
      - 100
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: sabnzbd.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sabnzbd-tls
          hosts:
            - sabnzbd.${SECRET_DOMAIN}
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      memory: 6144Mi
  persistence:
    config:
      enabled: true
      mountPath: /config
      size: 5Gi
    media:
      enabled: true
      type: nfs
      server: narya.${SECRET_INTERNAL_DOMAIN}
      path: /mnt/data/media
      mountPath: /data
    incomplete:
      enabled: true
      type: emptyDir
      mountPath: /incomplete
