---
helm:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  version: 1.5.1

backup:
  pvc: "sonarr-config"

values:
  automountServiceAccountToken: false
  controller:
    type: statefulset
  image:
    repository: ghcr.io/onedr0p/sonarr
    tag: 4.0.14.2938
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups:
      - 100
  service:
    main:
      ports:
        http:
          port: 8989
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: sonarr.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-tls
          hosts:
            - sonarr.${SECRET_DOMAIN}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 750m
      memory: 512Mi
  persistence:
    config:
      enabled: true
      mountPath: /config
      size: 5Gi
    media:
      enabled: true
      type: nfs
      server: narya.${SECRET_INTERNAL_DOMAIN}
      path: /mnt/data/media
      mountPath: /data
