---
helm:
  repo: https://charts.rook.io/release
  chart: rook-ceph-cluster
  version: v1.17.1

dependsOn:
  - name: observability-grafana-agent-cluster
  - name: storage-rook-ceph-operator

values:
  operatorNamespace: storage
  monitoring:
    enabled: true
    createPrometheusRules: true
    interval: 30s
  ingress:
    dashboard:
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      host:
        name: rook.${SECRET_DOMAIN}
        path: /
      tls:
        - secretName: rook-tls
          hosts:
            - rook.${SECRET_DOMAIN}
  cephClusterSpec:
    dashboard:
      enabled: true
      urlPrefix: /
      ssl: false
    storage:
      useAllNodes: false
      useAllDevices: false
      config:
        osdsPerDevice: "1"
      nodes:
        - name: vilya-w01
          devices:
            - name: sda
        - name: vilya-w02
          devices:
            - name: sda
        - name: vilya-w03
          devices:
            - name: sda
    placement:
      all:
        tolerations:
          - effect: NoSchedule
            operator: Exists
          - effect: NoExecute
            operator: Exists
    crashCollector:
      disable: false
    mgr:
      count: 1
    resources:
      mon:
        requests:
          cpu: 500m
          memory: 1300Mi
      osd:
        requests:
          cpu: 500m
          memory: 4Gi
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    name: csi-ceph-blockpool
    isDefault: true
    deletionPolicy: Delete
  cephBlockPools:
    - name: ceph-blockpool
      spec:
        failureDomain: osd
        replicated:
          size: 3
      storageClass:
        enabled: true
        name: ceph-block
        isDefault: true
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: storage
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: storage
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: storage
          csi.storage.k8s.io/fstype: ext4
          imageFeatures: layering
          imageFormat: "2"
  cephFileSystems: []
  cephObjectStores:
    - name: ceph-objectstore
      spec:
        metadataPool:
          failureDomain: osd
          replicated:
            size: 3
        dataPool:
          failureDomain: osd
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
        preservePoolsOnDelete: true
        gateway:
          port: 80
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 2Gi
          instances: 1
        healthCheck:
          bucket:
            interval: 60s
      storageClass:
        enabled: true
        name: ceph-bucket
        reclaimPolicy: Delete
        parameters:
          region: us-east-1
