---
helm:
  repo: https://piraeus.io/helm-charts/
  chart: snapshot-controller
  version: 4.0.2

dependsOn:
  - name: observability-grafana-agent-cluster

values:
  controller:
    serviceMonitor:
      create: true
  webhook:
    enabled: false
