---
helm:
  repo: https://backube.github.io/helm-charts/
  chart: volsync
  version: 0.12.1

dependsOn:
  - name: observability-grafana-agent-cluster
  - name: storage-snapshot-controller

values:
  metrics:
    disableAuth: true
