---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.6
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.10.2
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.225-192.168.1.230
