---
helm:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  version: 4.0.1

values:
  controllers:
    main:
      enabled: true
      type: deployment
      replicas: 1
      
      containers:
        main:
          image:
            repository: ghcr.io/alexxit/go2rtc
            tag: 1.9.9
            pullPolicy: IfNotPresent
          
          env:
            TZ: UTC
          
          resources:
            requests:
              gpu.intel.com/i915: 1
              cpu: 100m
              memory: 128Mi
            limits:
              gpu.intel.com/i915: 1
              cpu: 500m
              memory: 256Mi
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

      pod:
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          runAsNonRoot: true
          fsGroup: 65534
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups:
            - 44
            - 109

  service:
    main:
      enabled: true
      controller: main
      type: LoadBalancer
      annotations:
        "io.cilium/lb-ipam-ips": "192.168.2.16"
      ports:
        http:
          enabled: true
          port: 1984
          protocol: HTTP
          primary: true
        rtsp:
          enabled: true
          port: 8554
          protocol: TCP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: go2rtc.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: 1984
      tls:
        - secretName: go2rtc-tls
          hosts:
            - go2rtc.${SECRET_DOMAIN}

  configMaps:
    config:
      enabled: true
      data:
        go2rtc.yaml: |
          streams:
            elegoo:
              - ffmpeg:rtsp://192.168.50.36:554/video?#input=rtsp/udp#video=h264#media=video#resolution=960x540

  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      globalMounts:
        - path: /config
    
    dev-dri:
      enabled: true
      type: hostPath
      hostPath: /dev/dri
      globalMounts:
        - path: /dev/dri
