---
helm:
  repo: https://raw.githubusercontent.com/pulumi/pulumi-kubernetes-operator/gh-pages/
  chart: pulumi-kubernetes-operator
  version: 0.8.1

values:
  image:
    repository: pulumi/pulumi-kubernetes-operator
    tag: 1.15.0
  extraVolumes:
    - name: ssh-auth
      secret:
        secretName: pulumi-ssh-credentials
  extraVolumeMounts:
    - name: ssh-auth
      readOnly: true
      mountPath: "/etc/ssh/pulumi"
