---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: charlie-haley-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.charliehaley.dev
  timeout: 3m
