{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Temps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{sensor=\"Office Temp\"}",
     "legendFormat": "Office"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{sensor=\"Living Room Temp\"}",
     "legendFormat": "Living Room"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{sensor=\"Bedroom Temp\"}",
     "legendFormat": "Bedroom"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{sensor=\"\"}",
     "legendFormat": "Server Rack"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_mw{host=\"192.168.50.2:9999\"}",
     "legendFormat": "Desks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_mw{host=\"192.168.50.13:9999\"}",
     "legendFormat": "Rack"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{sensor=\"temp_bedroom\"}",
     "legendFormat": "Bedroom"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{sensor=\"temp_office\"}",
     "legendFormat": "Office"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.225:9100\"})",
     "legendFormat": "kube-master1"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.226:9100\"})",
     "legendFormat": "kube-master2"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.227:9100\"})",
     "legendFormat": "kube-master3"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.229:9100\"})",
     "legendFormat": "kube-worker1"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.230:9100\"})",
     "legendFormat": "kube-worker2"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.228:9100\"})",
     "legendFormat": "kube-worker3"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.1.240:9100\"})",
     "legendFormat": "nfsserver"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.50.18:9100\"})",
     "legendFormat": "zigbeemqtt"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage_mv{host=\"192.168.50.2:9999\"}",
     "legendFormat": "Desks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage_mv{host=\"192.168.50.13:9999\"}",
     "legendFormat": "Rack"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{sensor=\"temp_livingroom\"}",
     "legendFormat": "Living Room"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{sensor=\"temp_rack\"}",
     "legendFormat": "Server Rack"
    }
   ]
  },
  {
   "title": "Hall",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "occupancy{sensor=\"Hall Motion\"}",
     "legendFormat": "Hall"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.225:9100\"}[5m])) * 100)",
     "legendFormat": "kube-master1"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.226:9100\"}[5m])) * 100)",
     "legendFormat": "kube-master2"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.227:9100\"}[5m])) * 100)",
     "legendFormat": "kube-master3"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.229:9100\"}[5m])) * 100)",
     "legendFormat": "kube-worker1"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.230:9100\"}[5m])) * 100)",
     "legendFormat": "kube-worker2"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.228:9100\"}[5m])) * 100)",
     "legendFormat": "kube-worker3"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.1.240:9100\"}[5m])) * 100)",
     "legendFormat": "nfsserver"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.50.18:9100\"}[5m])) * 100)",
     "legendFormat": "zigbeemqtt"
    }
   ]
  },
  {
   "title": "Office",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "occupancy{sensor=\"Office Motion\"}",
     "legendFormat": "Office"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.225:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.225:9100\"})* 100)",
     "legendFormat": "kube-master1"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.226:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.226:9100\"})* 100)",
     "legendFormat": "kube-master2"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.227:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.227:9100\"})* 100)",
     "legendFormat": "kube-master3"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.229:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.229:9100\"})* 100)",
     "legendFormat": "kube-worker1"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.230:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.230:9100\"})* 100)",
     "legendFormat": "kube-worker2"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.228:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.228:9100\"})* 100)",
     "legendFormat": "kube-worker3"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.1.240:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.1.240:9100\"})* 100)",
     "legendFormat": "nfsserver"
    },
    {
     "expr": "100-(avg(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"192.168.50.18:9100\"})/avg(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"192.168.50.18:9100\"})* 100)",
     "legendFormat": "zigbeemqtt"
    }
   ]
  }
 ]
}